In [123]:
import numpy as np

txt = 'BIRTHDAYCAKE'.upper()

key = [[1,2],[3,4]]

In [124]:
split = [ord(i) for i in txt]

In [125]:
split

[66, 73, 82, 84, 72, 68, 65, 89, 67, 65, 75, 69]

In [126]:
split = np.reshape(split, (len(split)/2,2))

In [127]:
split

array([[66, 73],
       [82, 84],
       [72, 68],
       [65, 89],
       [67, 65],
       [75, 69]])

In [128]:
split = split - 65

In [129]:
split

array([[ 1,  8],
       [17, 19],
       [ 7,  3],
       [ 0, 24],
       [ 2,  0],
       [10,  4]])

In [130]:
enc = np.matmul(split,key)

In [131]:
enc

array([[ 25,  34],
       [ 74, 110],
       [ 16,  26],
       [ 72,  96],
       [  2,   4],
       [ 22,  36]])

In [132]:
enc = enc.tolist()

In [133]:
for i in range(len(enc)):
    for j in range(len(enc[i])):
        if (enc[i][j] >= 26):
            enc[i][j] = enc[i][j]%26 

In [134]:
enc

[[25, 8], [22, 6], [16, 0], [20, 18], [2, 4], [22, 10]]

In [135]:
for i in range(len(enc)):
    for j in range(len(enc[i])):
        enc[i][j] = chr(enc[i][j]+65)

In [136]:
enc

[['Z', 'I'], ['W', 'G'], ['Q', 'A'], ['U', 'S'], ['C', 'E'], ['W', 'K']]

In [137]:
fin = ''

for i in range(len(enc)):
    for j in range(len(enc[i])):
        fin += enc[i][j]

In [138]:
txt

'BIRTHDAYCAKE'

In [139]:
fin

'ZIWGQAUSCEWK'